/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import com.cosine.similarity.DocumentParser;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jigar
 */
public class QueryResullts extends javax.swing.JPanel {

    /**
     * Creates new form IndexChoice
     */
    JPanel upc;
    HashMap<String, Double> hm;
    DocumentParser dp;
    String userQuery;
    public QueryResullts(JPanel upc, HashMap<String, Double> cosineResults, DocumentParser dp, String userQuery) {
        initComponents();
        this.dp=dp;
        this.upc=upc;
        this.hm=cosineResults;  
        this.userQuery=userQuery;
        
        generateResults();
    }
    
    public void generateResults(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
//        Collections.sort(cosineResults);
//        TreeSet<Double> results=new TreeSet();
//        for(int i=0; i<cosineResults.length; i++){
//            System.out.println("cosineResults"+cosineResults[i]);                              
//        }
        
        for(Map.Entry<String,Double> entry : hm.entrySet()) {
            String key = entry.getKey();
            Double value = entry.getValue();
            Object row[]=new Object[2];
            row[0]=key;
            row[1]=value*100+"%";
            System.out.println(key + " => " + value);
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        yesJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        noJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        yesSearchJButton = new javax.swing.JButton();
        noSearchJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "docID", "Content Similarity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        yesJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        yesJButton.setText("Yes");
        yesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel2.setText("Was the result useful ?");

        noJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        noJButton.setText("No");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel3.setText("Continue Search?");

        yesSearchJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        yesSearchJButton.setText("Yes");
        yesSearchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesSearchJButtonActionPerformed(evt);
            }
        });

        noSearchJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        noSearchJButton.setText("No");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recommended docID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yesSearchJButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yesJButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noJButton)
                                    .addComponent(noSearchJButton)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesJButton)
                    .addComponent(jLabel2)
                    .addComponent(noJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yesSearchJButton)
                    .addComponent(noSearchJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesJButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<ArrayList<String>> likeListCollection=dp.saveLikes(hm);
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        for(ArrayList<String> likesList: likeListCollection){
            for(String docIds: likesList){
                Object row[]=new Object[1];
                row[0]=docIds;
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_yesJButtonActionPerformed

    private void yesSearchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesSearchJButtonActionPerformed
       //  TODO add your handling code here:
        HashMap<String,HashMap<String, Double>> searchedWordsList=dp.showNext(hm, userQuery);
        upc.remove(this);
        CardLayout layout = (CardLayout)upc.getLayout();
        layout.previous(upc);
        //PhraseSearch ps = new PhraseSearch(searchedWordsList);
    }//GEN-LAST:event_yesSearchJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton noJButton;
    private javax.swing.JButton noSearchJButton;
    private javax.swing.JButton yesJButton;
    private javax.swing.JButton yesSearchJButton;
    // End of variables declaration//GEN-END:variables
}
