/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.FileRead;
import Business.Search;
import Business.SpellChecker;
import com.cosine.similarity.DocumentParser;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.JPanel;

/**
 *
 * @author Jigar
 */
public class SearchChoice extends javax.swing.JPanel {

    /**
     * Creates new form SearchChoice
     */
    JPanel upc;
    //HashMap<String, HashMap<String,ArrayList<Integer>>> hm;
    DocumentParser dp;
    FileRead fr;
    Search search=new Search();
    
    public SearchChoice(JPanel upc, FileRead fr, DocumentParser dp){
       initComponents();
       this.upc=upc;
       this.fr=fr;
       this.dp=dp;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quickSearch = new javax.swing.JButton();
        detailSearchJButton = new javax.swing.JButton();
        quickSearchJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFIDF = new javax.swing.JButton();

        quickSearch.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        quickSearch.setText("Quick Search");
        quickSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSearchActionPerformed(evt);
            }
        });

        detailSearchJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        detailSearchJButton.setText("Detailed Search");
        detailSearchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailSearchJButtonActionPerformed(evt);
            }
        });

        quickSearchJTextField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setText("Word Search");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel3.setText("Time taken to create Inverted Index");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel4.setText("jLabel4");

        TFIDF.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        TFIDF.setText("Relevant Documents");
        TFIDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(quickSearchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quickSearch)
                                .addGap(54, 54, 54)
                                .addComponent(detailSearchJButton)))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TFIDF)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quickSearchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quickSearch)
                    .addComponent(detailSearchJButton))
                .addGap(72, 72, 72)
                .addComponent(TFIDF)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quickSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSearchActionPerformed
        // TODO add your handling code here:
        String quickSearch=quickSearchJTextField.getText();
        ArrayList<String> docIDs = search.singleWordQuickSearch(quickSearch, fr.getHm());
        
        QuickSearch qs = new QuickSearch(upc,docIDs);
        upc.add("QuickSearch",qs);
        CardLayout layout = (CardLayout)upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_quickSearchActionPerformed

    private void TFIDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIDFActionPerformed
        // TODO add your handling code here:

        RelevantDocs relevantDocs = new RelevantDocs(upc,fr);
        upc.add("RelevantDocs",relevantDocs);
        CardLayout layout = (CardLayout)upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_TFIDFActionPerformed

    private void detailSearchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailSearchJButtonActionPerformed
        // TODO add your handling code here:
        String quickSearch=quickSearchJTextField.getText();
        TreeMap<String, ArrayList<Integer>> tm = search.singleWordSearch(quickSearch, fr.getHm());
        System.out.println("tm"+tm);
        
        DetailSearch ds = new DetailSearch(upc,tm);
        upc.add("QuickSearch",ds);
        CardLayout layout = (CardLayout)upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_detailSearchJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TFIDF;
    private javax.swing.JButton detailSearchJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton quickSearch;
    private javax.swing.JTextField quickSearchJTextField;
    // End of variables declaration//GEN-END:variables
}
